import { test, expect } from '@playwright/test';

test('Hoffmann French press is discovered and guides steep, skim, settle, and no-plunge serving', async ({ page, request }) => {
  await page.clock.install({ time: new Date(Date.now() - 60 * 60 * 1000) });
  await page.goto('/');
  await page.getByRole('button', { name: /French Press/ }).click();
  await expect(page.getByLabel('Coffee beans')).toHaveValue('30');
  await expect(page.locator('#water')).toHaveText('500 g');
  await expect(page.locator('#grind')).toHaveText('Medium');
  await expect(page.getByLabel('Water temperature')).toHaveValue('212');
  await expect(page.locator('#recipe-attribution')).toContainText('James Hoffmann');
  await expect(page.getByRole('link', { name: 'Original recipe' })).toHaveAttribute('href', 'https://www.youtube.com/watch?v=st571DYYTR8');
  await expect(page.locator('#timing')).not.toContainText('last drip');
  await expect(page.locator('#prep')).toContainText('freshly boiled water');
  await page.getByLabel('Coffee beans').fill('15');
  await expect(page.locator('#water')).toHaveText('250 g');
  await page.getByLabel('Coffee beans').fill('30');
  await page.setViewportSize({ width: 320, height: 720 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Start brewing' }).click();
  const brewId = await page.evaluate(() => JSON.parse(localStorage.getItem('morning-coffee-v1')).session.brewId);
  await expect.poll(async () => (await request.get(`/api/brews/${brewId}`)).status()).toBe(200);
  await expect(page.locator('#instruction-title')).toHaveText('Add all the water');
  await page.clock.fastForward(30000);
  await expect(page.locator('#instruction-title')).toHaveText('Steep undisturbed');
  await page.clock.fastForward(210000);
  await expect(page.locator('#instruction-title')).toHaveText('Break the crust and skim');
  await page.clock.fastForward(600000);
  await expect(page.locator('#instruction-title')).toHaveText('Break the crust and skim');
  await expect(page.locator('#progress')).toHaveAttribute('value', '40');
  await page.reload();
  await expect(page.locator('#instruction-title')).toHaveText('Break the crust and skim');
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Done → Continue' })).toBeDisabled();
  const frozen = await page.locator('#clock').textContent();
  await page.clock.fastForward(60000);
  await expect(page.locator('#clock')).toHaveText(frozen);
  await page.getByRole('button', { name: 'Resume' }).click();
  await page.getByRole('button', { name: 'Done → Continue' }).click();
  await expect(page.locator('#instruction-title')).toHaveText('Let the grounds settle');
  await expect(page.locator('#timing')).toContainText('5:00 left');
  await page.reload();
  await expect(page.locator('#instruction-title')).toHaveText('Let the grounds settle');
  await expect(page.locator('#instruction')).toContainText('five to eight minutes');
  await page.clock.fastForward(299000);
  await expect(page.locator('#instruction-title')).toHaveText('Let the grounds settle');
  await page.clock.fastForward(1000);
  await expect(page.locator('#instruction-title')).toHaveText('Serve gently, do not plunge');
  await expect(page.locator('#instruction')).toContainText('Do not push it down');
  await expect(page.locator('#target')).toHaveText('500 g');
  await page.clock.fastForward(60000);
  await expect(page.locator('#instruction-title')).toHaveText('Serve gently, do not plunge');
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: 'Finish brew', exact: true }).click();
  await expect(page.locator('#status')).toHaveText('BREWING');
  await page.getByRole('button', { name: 'Done → Continue' }).click();
  await expect(page.getByRole('button', { name: 'Done → Continue' })).toBeHidden();
  await page.reload();
  await expect(page.locator('#instruction-title')).toHaveText('Complete the final step.');
  await page.getByRole('button', { name: 'Finish brew', exact: true }).click();
  await expect(page.locator('#instruction')).toContainText('do not plunge');
  await expect.poll(async () => (await (await request.get(`/api/brews/${brewId}`)).json()).status).toBe('completed');
  const brew = await (await request.get(`/api/brews/${brewId}`)).json();
  expect(brew.temperatureF).toBe(212);
  expect(brew.recipe.steps.filter(step => step.manual)).toHaveLength(2);
  expect(brew.elapsedSeconds).toBeGreaterThanOrEqual(1200);
  expect(brew.elapsedSeconds).toBeLessThan(1210);
});
