import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';

test('iced V60 retains its own dose and grind, restores timer, and replays from journal', async ({ page, request }) => {
  const bag = await (await request.post('/api/bags', { data: { roaster: 'Iced test', name: randomUUID() } })).json();
  await page.clock.install({ time: new Date(Date.now() - 10 * 60 * 1000) });
  await page.goto('/');
  await expect(page.getByLabel('On the counter')).toHaveValue(bag.id);
  await page.getByText('Your grinder setting').click();
  await page.getByLabel('Save a dial setting').fill('Hot 16');
  await page.getByLabel('V60 recipe').selectOption('japanese-iced');
  await expect(page.getByLabel('Coffee beans')).toHaveValue('15');
  await expect(page.locator('#water')).toHaveText('150 g');
  await expect(page.locator('#ice-guide')).toContainText('75 g brewing ice');
  await expect(page.locator('#ratio')).toHaveText('1 : 15');
  await expect(page.locator('#grind')).toHaveText('Encore · 13');
  await page.getByLabel('Save a dial setting').fill('Iced 12');
  await page.getByLabel('V60 recipe').selectOption('hot');
  await expect(page.getByLabel('Coffee beans')).toHaveValue('20');
  await expect(page.locator('#grind')).toHaveText('Hot 16');
  await expect(page.locator('#ice-guide')).toBeHidden();
  await page.getByLabel('V60 recipe').selectOption('japanese-iced');
  await page.getByRole('button', { name: /Chemex/ }).click();
  await expect(page.getByLabel('V60 recipe')).toBeHidden();
  await expect(page.locator('#water')).toHaveText('480 g');
  await page.getByRole('button', { name: /V60/ }).click();
  await expect(page.getByLabel('V60 recipe')).toHaveValue('japanese-iced');
  await expect(page.locator('#grind')).toHaveText('Iced 12');
  await page.getByRole('button', { name: 'Start brewing' }).click();
  await expect(page.getByLabel('V60 recipe')).toBeDisabled();
  const id = await page.evaluate(() => JSON.parse(localStorage.getItem('morning-coffee-v1')).session.brewId);
  await expect.poll(async () => (await request.get(`/api/brews/${id}`)).status()).toBe(200);
  await page.clock.fastForward(30000);
  await expect(page.locator('#target')).toHaveText('90 g');
  await expect(page.locator('#rate')).toHaveText('3.0 g/s');
  await page.reload();
  await expect(page.getByLabel('V60 recipe')).toHaveValue('japanese-iced');
  await expect(page.locator('#target')).toHaveText('90 g');
  await page.clock.fastForward(30000);
  await expect(page.locator('#target')).toHaveText('150 g');
  await page.clock.fastForward(100000);
  await page.getByRole('button', { name: 'Finish brew', exact: true }).click();
  await expect(page.locator('#instruction')).toContainText('top with ice');
  await expect.poll(async () => (await (await request.get(`/api/brews/${id}`)).json()).status).toBe('completed');
  const record = await (await request.get(`/api/brews/${id}`)).json();
  expect(record).toMatchObject({ variant: 'japanese-iced', dose: 15, water: 150, ice: 75, totalWater: 225, grindSetting: 'Iced 12' });
  await page.getByRole('button', { name: 'Make another cup' }).click();
  await page.getByLabel('V60 recipe').selectOption('hot');
  await page.getByRole('link', { name: 'Journal', exact: true }).click();
  const card = page.locator('.journal-card').filter({ hasText: bag.name });
  await expect(card).toContainText('Japanese Iced');
  await expect(card).toContainText('150 g hot water');
  await expect(card).toContainText('75 g brewing ice');
  await card.getByRole('button', { name: 'Brew again' }).click();
  await expect(page.getByLabel('V60 recipe')).toHaveValue('japanese-iced');
  await expect(page.getByLabel('Coffee beans')).toHaveValue('15');
  await expect(page.locator('#grind')).toHaveText('Iced 12');
  await page.setViewportSize({ width: 320, height: 720 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
